{% set name = "rattler-build-conda-compat" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nichmor/rattler-build-conda-compat/releases/download/v{{ version }}/rattler_build_conda_compat-{{ version }}.tar.gz
  sha256: 476b836fd8e003ad91fb8c1304a1789a07afd9478ba37c599689f2354b6d47b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.25.0
  run:
    - python >=3.8
    - rattler-build
    - conda-build
    - pytest


test:
  imports:
    - rattler_build_conda_compat.loader
    - rattler_build_conda_compat.render
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/nichmor/rattler-build-conda-compat
  summary: 'rattler-build module which offer compatibility with conda-smithy'
  description: |
    rattler-build module which offer compatibility with conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tdejager
    - nichmor
